version: "3.9"
services:
  notifier:
    build: .
    container_name: twitch-discord-notifier
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates:ro
